stages:
  - report

weekly_report:
  stage: report
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - bash ./git-contribution-report.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - when: manual